title: use \BNE\PHP;
description: We're a Brisbane meetup for everything PHP!
url: "https://brisphp.com"
github_username:  brisphp
author: ''

header_pages:
  - about.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seotag
